# Generated by Django 5.2 on 2025-04-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_branch_student_district_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
